---

- name: SNORT SOURCE | Manage user
  import_tasks: users.yml

- name: SNORT SOURCE | Install prerequisites packages
  package:
    name:
      - gcc
      - flex
      - bison
      - libdnet
      - libpcre3-dev
      - zlib1g-dev
      - openssl
      - libssl-dev
      - libnghttp2-dev
      - libdumbnet-dev
      - luajit
      - libluajit-5.1-dev
      - libdaq2
      - libpcap-dev
    state: present

- name: SNORT SOURCE | Download and extract sources
  unarchive:
    src: "{{ item.src }}"
    dest: /opt
    owner: root
    group: root
    remote_src: yes
    creates: "{{ item.creates }}"
  with_items:
    - { src: "{{ snort_daq_source }}", creates: "/opt/daq-{{ snort_daq_version }}" }
    - { src: "{{ snort_source }}", creates: "/opt/snort-{{ snort_version }}" }

- name: SNORT SOURCE | Compile DAQ sources
  shell: ./configure && make && make install
  args:
    chdir: /opt/daq-{{ snort_daq_version }}
    creates: /opt/daq-{{ snort_daq_version }}/Makefile

- name: SNORT SOURCE | Compile Snort sources
  shell: ./configure --enable-sourcefire && make && make install
  args:
    chdir: /opt/snort-{{ snort_version }}
    creates: /opt/snort-{{ snort_version }}/Makefile

- name: SNORT SOURCE | Manage symlink
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  with_items:
    - { src: /usr/local/bin/snort, dest: /usr/sbin/snort }
    - { src: "/opt/snort-{{ snort_version }}/etc", dest: /etc/snort }
